### PR TITLE
(DNM) Fix for Issue #216

### PR DESCRIPTION
**Pull request by ZachBray**
**Do not merge until target is fixed (currently targets v1.2.0)**

- Added tests proving problem with behaviour
- Changed translation to avoid `this` referring to wrong thing

@renaudpawlak, I did the fixes against v1.2.0. Please let me know if there is anything you'd like me to change? For the project I'm working on it'd be great to have access to a v1.2.1 with the fixes in. If this is possible, please let me know where to retarget my PR.

### CODE REVIEW

**Comment by renaudpawlak** [comment]
Hi Zach. Many thanks. I have created a 1.2.1 branch if you want to PR in it (hopefully I did the right thing). I will deploy a 1.2.1 version when ready.

**Comment by lgrignon** [comment]
I will merge & deploy. Thanks for contributing!

**Comment by lgrignon** [comment]
Everything seems OK, thanks. I deploy JSweet 1.2.1 right now.

**Comment by lgrignon** [comment]
Integrated in JSweet 2.0.0 (master) through 8041fba

**Comment by ZachBray** [comment]
@lgrignon Thanks for doing that. I'll try to check and close today.

**Pull request merged**
