### PR TITLE
header missing for default method accessing superclass enum #530

### PR DESCRIPTION
**Pull request by jmstark**
I pushed a fix that so far works for my code but I suspect that the header inclusion should happen at another place or that it might not work for all cases.
#530

### CODE REVIEW

**Comment by lgrignon** [comment]
Unit tests are apparently failing :/ 
Did you run all of them locally?

**Comment by lgrignon** [comment]
It seems to be a problem on Travis side, I will try again later.

Thank you very much for submitting this.

**Comment by lgrignon** [comment]
Could you please update from develop branch? I fixed the Travis build problem

**Comment by jmstark** [comment]
Thanks, I merged develop from upstream. Looks like it passed.

**Comment by lgrignon** [comment]
Thanks!

**Pull request merged**
