### PR TITLE
@Inline

### PR DESCRIPTION
**Pull request by schaumb**
This Idea comes from the previous #452 PR, but in general.

@ Inline is an annotation which tells jsweet to force inline the function body to the caller target.
 This means these functions are not exist, but can be use them as any other function in same compilation unit, without limitations.

Example:
```
package java;

import jsweet.lang.Inline;

import static def.dom.Globals.console;

public class Test {
    private static int result = 0;
    public static void main(String[] args) {
        console.info(multiple(20, 13));
    }

    @Inline
    public static int multiple(int first, int second) {
        result = first;
        for (int i = 1; i < second; ++i) {
            result = add(result, first);
        }
        return result;
    }

    @Inline
    public static int add(int first, int second) {
        if (second > 0) {
            return add(first + 1, second - 1);
        } else if (second < 0) {
            return add(first - 1, second + 1);
        } else {
            return first;
        }
    }
}
```
compiles to:
```
namespace java {
    export class Test {
        static result : number = 0;

        public static main(args : string[]) {
            console.info(((function $$INLINED$$Test$multiple(first : number, second : number) {
                Test.result = first;
                for(let i : number = 1; i < second; ++i) {
                    Test.result = ((function $$INLINED$$Test$add(first : number, second : number) {
                        if(second > 0) {
                            return ($$INLINED$$Test$add.call(this, first + 1, second - 1));
                        } else if(second < 0) {
                            return ($$INLINED$$Test$add.call(this, first - 1, second + 1));
                        } else {
                            return first;
                        }
                    }).call(this, Test.result, first));
                };
                return Test.result;
            }).call(this, 20, 13)));
        }
    }
    Test["__class"] = "java.Test";

}
```

I [hide](https://github.com/cincheo/jsweet/compare/master...schaumb:patch-2?expand=1#diff-031be2405393703e0cff0db57e8d26fdR378) a Promise specific feature, which enables to return a non-Promise object from an async function.
If a function annotated with @ Inline and @ Async, and if the result type is not Promise, then the inlined function got a "await" prefix.

Example
```
package java;

import def.js.Promise;
import jsweet.lang.Async;
import jsweet.lang.Inline;
import jsweet.util.Lang;

import java.util.function.Function;

import static def.dom.Globals.console;
import static jsweet.util.Lang.await;

public class Test {
    private static Promise<Integer> result = Promise.resolve(0);
    public static void main(String[] args) {
        console.info(multiple(Promise.resolve(20), Promise.resolve(13)));
    }

    @Inline
    @Async
    public static Promise<Integer> multiple(Promise<Integer> first, Promise<Integer> second) {
        result = first;
        int sec = await(second);
        for (int i = 1; i < sec; ++i) {
            int res = add(result, first);
            result = Promise.resolve(res);
        }
        return result;
    }

    @Inline
    @Async
    public static Integer add(Promise<Integer> i1, Promise<Integer> i2) {
        return await(Promise.all(Lang.<Promise.IterablePromiseLikeT<Integer>> any(new Promise[]{i1, i2}))
                .then((Function<Integer[], Integer>) (Integer[] iArr) -> {
                    if (iArr[1] > 0) {
                        return add(Promise.resolve(iArr[0] + 1), Promise.resolve(iArr[1] - 1));
                    } else if (iArr[1] < 0) {
                        return add(Promise.resolve(iArr[0] - 1), Promise.resolve(iArr[1] + 1));
                    } else
                        return iArr[0];
                }));
    }
}
```
to
```
namespace java {
    export class Test {
        static result : Promise<number>; public static result_$LI$() : Promise<number> { if(Test.result == null) Test.result = Promise.resolve(0); return Test.result; };

        public static main(args : string[]) {
            console.info(((async function $$INLINED$$Test$multiple(first : Promise<number>, second : Promise<number>) {
                Test.result = first;
                let sec : number = <any>(await second);
                for(let i : number = 1; i < sec; ++i) {
                    let res : number = (await (async function $$INLINED$$Test$add(i1 : Promise<number>, i2 : Promise<number>) {
                        return <any>(await Promise.all(<any>((<any>([i1, i2])))).then(<any>((iArr) => {
                            if(iArr[1] > 0) {
                                return ($$INLINED$$Test$add.call(this, Promise.resolve(iArr[0] + 1), Promise.resolve(iArr[1] - 1)));
                            } else if(iArr[1] < 0) {
                                return ($$INLINED$$Test$add.call(this, Promise.resolve(iArr[0] - 1), Promise.resolve(iArr[1] + 1)));
                            } else return iArr[0];
                        })));
                    }).call(this, Test.result_$LI$(), first));
                    Test.result = Promise.resolve(res);
                };
                return Test.result_$LI$();
            }).call(this, Promise.resolve(20), Promise.resolve(13))));
        }
    }
    Test["__class"] = "java.Test";

}
```

### CODE REVIEW

**Comment by schaumb** [comment]
I think it is not going to be the final version. It need to be refactoring the common used functionalities.

**Comment by lgrignon** [comment]
This sounds really interesting! I have to dive deeper into it, but thanks :)

**Comment by lgrignon** [comment]
Is it the final version or do you want to add some features or refactoring? Please tell me, I will review as soon as possible when you finish.

**Comment by schaumb** [comment]
It is not the final version. I want to do refactoring.

**Comment by lgrignon** [comment]
Hello @schaumb did you progress on this?

**Comment by schaumb** [comment]
Hi, I'm not.
The concept needed for [j4ts-concurrent](https://github.com/j4ts/j4ts-concurrent), but it is currently not in track.

There was some parameter issue, and I duplicate some code which requires a refactor.
And probably need some test for it. ;)

**Comment by lgrignon** [comment]
Hey @schaumb 
I hope you are doing fine in those troubled times. 

I was thinking of closing this PR since it requires additional work, and would not be ready to merge soon. Is it ok for you?

**Comment by schaumb** [comment]
Hi!

It is OK, you can close it.
I'm not tried jsweet3, I stucked in my own stable version (jsweet+j4ts) , which is currently enough for me.

If I can help with the migration, you can reach me in e-mail.

**Comment by lgrignon** [comment]
Thanks for your answer. I am glad to here that you are still using JSweet :)

About JSweet 3, I will probably release it without j4ts at start, and opened an issue here in case some contributors are willing to help but I won't spend more time on this soon:
https://github.com/j4ts/j4ts/issues/56

I don't think I have your email by the way :)

**Comment by schaumb** [comment]
I sent you a Linkedin message @lgrignon

**Pull request closed without merging**
