### PR TITLE
StringBuilder macro fixes

### LINKED ISSUE #484: StringBuilder, invalid type mapping
Hello!

Again an observation about a minor inconsistency.
Input to the transpiler:
```
StringBuilder b = new StringBuilder();
```
Output of the transpiler:
```
let b : { str: string } = { str: "", toString: function() { return this.str; } };
```
Typescript error in the translated code:
```
'{ str: string; toString: () => any; }' is not assignable to type '{ str: string; }'
```
The source of this problem is probably the adapter `RemoveJavaDependenciesAdapter` (I couldn't figure out an other adapter that maps `StringBuilder`).

### PR DESCRIPTION
**Pull request by mdudzinski**
* Add 'lastIndexOf' case to StringBuilder macro
* Fix #484

### CODE REVIEW

**Comment by mdudzinski** [comment]
Crap, I thought that the presence of `toString()` in the new class macro was an oversight but now I see  it is needed to handle java implicit calls to `toString()`. Any ideas how to fix #484 ?

**Comment by mdudzinski** [comment]
Okay, another try 😄

**Comment by mdudzinski** [comment]
Checked the failed build:

`The job exceeded the maximum log length, and has been terminated.`

Seems like it is not related with the PR but please correct me if I am wrong.

**Comment by mdudzinski** [comment]
Tests pass locally on my machine (`mvn clean test`).

**Comment by lgrignon** [comment]
Thanks for contributing!

**Pull request merged**
