### PR TITLE
Fix Crush when handle Arrays.sort only have one argument

### PR DESCRIPTION
**Pull request by facetothefate**
#421

### CODE REVIEW

**Comment by lgrignon** [comment]
Thanks. Look nice!

Could you please add a unit test to cover this case and I will merge it right after

**Comment by facetothefate** [comment]
Sure!

**Comment by facetothefate** [comment]
Btw, where should I put the unit test ? Thanks.

**Comment by lgrignon** [comment]
You will find example right there:
https://github.com/cincheo/jsweet/tree/master/transpiler/src/test/java/org/jsweet/test/transpiler

Thanks again for your contribution :)

**Comment by lgrignon** [comment]
Hey, 
thank you for adding this test. However I think it belongs to https://github.com/facetothefate/jsweet/blob/2cf334268af30d2d0a6be8a660d9dc54847c22cf/transpiler/src/test/java/org/jsweet/test/transpiler/NativeStructuresTests.java, with other collections test

Sorry to ask you this last modif :) I merged right after it.

Thanks again.
Bye

**Comment by lgrignon** [comment]
Wow, still not merged ^^ I will move your test and merge. Thanks

**Comment by lgrignon** [comment]
Integrated with b246963f87303bb04caee035c5492eb246b518b8

**Pull request merged**
