### PR TITLE
Support for string enums (typescript)

### PR DESCRIPTION
**Pull request by basti-schneider**
This pull request enables the support for generating string enums (https://www.typescriptlang.org/docs/handbook/enums.html#string-enums) in typescript.

### CODE REVIEW

**Comment by renaudpawlak** [comment]
Nice work. It will be a great addition for the upcoming version 1.4 :)
Thanks.

**Comment by renaudpawlak** [comment]
Oops. It breaks the build.

**Comment by renaudpawlak** [comment]
I think we just need to update the core lib because you added an annotation. That's nothing. I will take care of it ASAP.

**Comment by basti-schneider** [comment]
Oh, I'll have a look at this in the evening.

**Comment by basti-schneider** [comment]
Ah right I noticed this and only changed it in my repo

**Comment by renaudpawlak** [comment]
Don't worry, I'll take care of it because it requires deploying a new core-lib version.

**Comment by basti-schneider** [comment]
Okay thanks  for merging :)

**Comment by renaudpawlak** [comment]
It should work now... but it is the other PR that poses problem :) I'll take a look at it too.

**Pull request merged**
