### PR TITLE
Return removed value in the maps remove macro

### PR DESCRIPTION
**Pull request by mdudzinski**
A simple fix that makes the native Map `remove` implementation closer to the JDK one.

### CODE REVIEW

**Comment by lgrignon** [comment]
Thanks for all your contributions. I will take a look asap.
Can you make sure unit tests pass please? Build is broken (but it could break for some reason on travis, please try in your ide)

**Comment by mdudzinski** [comment]
@lgrignon You're welcome!

Yeah tests pass locally on my machine.

Have you had a chance to look at my comment in the other PR? -> https://github.com/cincheo/jsweet/pull/485#issuecomment-426906650

It seems like the build failures are caused by the output log being too long. It looks like the last two master builds have suffered from the same problem ->
https://travis-ci.org/cincheo/jsweet/builds.

**Comment by lgrignon** [comment]
I saw that error before and thought it was a warning. I think we should turn transpiler verbosity off for travis builds. Should be pretty easy using a sys prop

**Comment by lgrignon** [comment]
Thanks for contributing!

I will deploy now

**Pull request merged**
