### PR TITLE
Non static method reference

### PR DESCRIPTION
**Pull request by chfeiler**
Fix for bug in issue #483.
A test is included which tests several different types of method references.

### CODE REVIEW

**Comment by renaudpawlak** [comment]
Looks like a great PR. I don't get why you need an adapter in your test though. Can you explain in a few words?

**Comment by chfeiler** [comment]
Thanks for the quick response!
I figured an easy and quick way to test different kinds of method references is to use a stream.
Hence, the tested class contains this code:
```java
        l = l.stream()
                .map(SomeStringWrapper::new) // constructor reference
                .filter(SomeStringWrapper::startsWithDot) // instance member reference
                .map(SomeStringWrapper::getS) // again instance member reference
                .map(nsb::add) // instance member reference of an existing object
                .filter(SomeStringWrapper::stringContainsA) // class/static member reference
                .collect(Collectors.toList());
```
However, to the best of my knowledge the JSweet transpiler does not contain a default mapping for streams. Therefore, the adapter in the test removes the `java.util.stream.Stream` dependencies. Since `map` and `filter` are available for arrays in JS, the adapter simply removes the `.stream()` and the `.collect(Collectors.toList())` invocations.

**Comment by chfeiler** [comment]
For simplicity, I removed the adapter and changed the test slightly.

**Comment by chfeiler** [comment]
Is this PR ready for being accepted (the test doesn't use an adapter anymore)?

**Comment by lgrignon** [comment]
Oh sorry, it seems this PR just got lost :)

This seems perfect, thanks a lot for your contribution!

It will be deployed in a few hours.

**Comment by chfeiler** [comment]
Thanks a lot:)

**Pull request merged**
